package genetictank;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

public class GeneticAlgorithm {
	/**
	 * Params to geneticAlgorithm
	 */
	private int POPULATION_SIZE = 20;
	private int MIN_BULLET_POWER = 1;
	private int MAX_BULLET_POWER = 3;
	private int MAX_NUMBER_OF_GENERATIONS = 9999;
	private int RENEWER_POPULATION_RATE = 20;
	private int CHROMOSOME_PARAMS_SIZE = 9; // QUANTITY OF MOVES AND ROTATIONS THAT A CHROMOSOME MUST HAVE
	private int MUTATION_RATE = 20;

	private Population population;
	private int numberOfGenerations =0;

	public void generateRandomPopulation(){
		population = new Population(POPULATION_SIZE);
		for(int i = 0; i < POPULATION_SIZE; i++){
			population.addChromosome(generateRandomChromosome(i));
		}
	}

	private Chromosome generateRandomChromosome(int id) {
		Chromosome chromosome = new Chromosome(id);
		List<Double> rotations = new ArrayList<Double>();
		List<Double> moves = new ArrayList<Double>();

		for(int i = 0; i < CHROMOSOME_PARAMS_SIZE; i++) {
			rotations.add((double)randomInt(0, 180));
			moves.add((double)randomInt(100, 500));
		}

		chromosome.setRotations(rotations);
		chromosome.setDistances(moves);
		chromosome.setBulletPower(randomInt(MIN_BULLET_POWER, MAX_BULLET_POWER));

		return chromosome;

	}
	
	private void renewPopulation(){
		if(population == null ){
			generateRandomPopulation();
			return;
		}
		
		List<Chromosome> bestsChromosomes = selection(population);
		List<Chromosome> children = new ArrayList<Chromosome>();
		int size = bestsChromosomes.size();
		
		while(children.size() < bestsChromosomes.size()){
			//TODO implement the roulette wheel method
			Chromosome parent1 = bestsChromosomes.get(randomInt(0, size));
			Chromosome parent2 = bestsChromosomes.get(randomInt(0, size));
			
			Chromosome[] newBorns = crossOver(parent1, parent2);
			children.add(newBorns[0]);
			children.add(newBorns[1]);
		}
		
		List<Chromosome> newPopulation = population.getPopulation();
		
		for (int i = 0; i < children.size(); i++) {
			newPopulation.set(i, children.get(i));
		}
		for (int i = 0; i < newPopulation.size(); i++) {
			newPopulation.get(i).setFitness(0);
		}
		numberOfGenerations++;
		population.setPopulation(newPopulation);
	}
	
	public int getNumberOfGenerations() {
		return numberOfGenerations;
	}

	public void setNumberOfGenerations(int numberOfGenerations) {
		this.numberOfGenerations = numberOfGenerations;
	}

	/**
	 * Select the best chromosomes from a given population based on the renewer rate
	 * @param population
	 * @return
	 */
	private List<Chromosome> selection(Population population){
		Collections.sort(population.getPopulation());
		return population.getPopulation().subList(RENEWER_POPULATION_RATE, POPULATION_SIZE-1);
	}
	
	/**
	 * returns a list with the two chromosomes generated by the crossOver of the two given ones 
	 * @param c1 
	 * @param c2
	 * @return
	 */
	private Chromosome[] crossOver(Chromosome c1, Chromosome c2){
		Chromosome r1 = new Chromosome(randomInt(0, 999999999));
		Chromosome r2 = new Chromosome(randomInt(0, 999999999));
		
		int splitPoint = randomInt(0, CHROMOSOME_PARAMS_SIZE-1);
		
		List<Double> rotationR1 = new ArrayList<Double>();
		List<Double> rotationR2 = new ArrayList<Double>();
		List<Double> distanceR1 = new ArrayList<Double>();
		List<Double> distanceR2 = new ArrayList<Double>();
		
		for (int i = 0; i < splitPoint; i++) {
			rotationR1.add(c1.getNextRotations().get(i));
			distanceR1.add(c1.getDistances().get(i));
		
			rotationR2.add(c2.getNextRotations().get(i));
			distanceR2.add(c2.getDistances().get(i));
		}
		
		for (int i = splitPoint; i < CHROMOSOME_PARAMS_SIZE; i++) {
			rotationR1.add(c2.getNextRotations().get(i));
			distanceR1.add(c2.getDistances().get(i));
			
			rotationR2.add(c1.getNextRotations().get(i));
			distanceR2.add(c1.getDistances().get(i));
		}
		
		r1.setDistances(distanceR1);
		r1.setRotations(rotationR1);
		
		r2.setRotations(rotationR2);
		r2.setRotations(rotationR2);
		
		if(randomInt(0,1)!= 0){
			r1.setBulletPower(c1.getBulletPower());
			r2.setBulletPower(c2.getBulletPower());
		}else{
			r1.setBulletPower(c2.getBulletPower());
			r2.setBulletPower(c1.getBulletPower());
		}
		
		mutate(r1);
		mutate(r2);
		
		Chromosome[] result = {r1,r2};
		return result;
	}
	
	private void mutate(Chromosome c){
		boolean isUpToMutation = randomInt(0, MUTATION_RATE) == 5;
		if(isUpToMutation){
			int rotationSize = c.getNextRotations().size()-1;
			int distancesSize = c.getDistances().size()-1;
			Double newRotation = (double) randomInt(0, 180);
			Double newDistance = (double) randomInt(100, 500);
			c.getNextRotations().set(randomInt(0, rotationSize), newRotation);
			c.getDistances().set(randomInt(0, distancesSize),newDistance);			
		}
	}

	private int randomInt(int start, int end) {
		Random rand = new Random();
		return rand.nextInt(end - start + 1) + start;
	}

}
